# Generated by Django 5.0.6 on 2024-10-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_criterion_rubric_event_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
