# Generated by Django 5.0.6 on 2024-10-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_criterion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
