# Generated by Django 5.0.6 on 2024-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_criterion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_barcodes/'),
        ),
    ]
