# Generated by Django 5.0.6 on 2024-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrcodes/'),
        ),
    ]
