# Generated by Django 5.0.6 on 2024-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_event_barcode_image_event_qr_code_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
