# Generated by Django 5.0.6 on 2024-11-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rfid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_RFID', to=settings.AUTH_USER_MODEL),
        ),
    ]
