# Generated by Django 5.0.6 on 2024-11-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rfid_is_available_alter_rfid_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_event', to='core.event'),
        ),
    ]
