# Generated by Django 5.0.6 on 2024-11-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rfid_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfid',
            old_name='player_name',
            new_name='participant',
        ),
    ]
