# Generated by Django 5.0.6 on 2024-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_player_name_rfid_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
