# Generated by Django 5.0.6 on 2024-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_rfid_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='rfid_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
